name: CI
on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - beta
      - main
      - master
jobs:
  build:
    uses: plumelo/dev/.github/workflows/node.yml@master
    secrets: inherit
